CREATE TABLE Locations
(
	id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	name NVARCHAR(300) NOT NULL
)

CREATE TABLE Travels
(
	id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	description NVARCHAR(1000),
	start DATETIME2 NOT NULL DEFAULT GETDATE(),
	finish DATETIME2 NOT NULL DEFAULT GETDATE(),
	location_from_id UNIQUEIDENTIFIER NOT NULL REFERENCES Locations(id),
	location_to_id UNIQUEIDENTIFIER NOT NULL REFERENCES Locations(id),
	user_id NVARCHAR(300) NOT NULL
)

INSERT INTO Locations (id, name) VALUES (NEWID(), 'Warszawa');
INSERT INTO Locations (id, name) VALUES (NEWID(), 'Poznañ');